/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mission = IDL.Record({
  'id' : IDL.Text,
  'completed' : IDL.Bool,
  'playerName' : IDL.Text,
});
export const Player = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });

export const idlService = IDL.Service({
  'createOrUpdateMission' : IDL.Func([Mission], [], []),
  'createOrUpdatePlayer' : IDL.Func([Player], [], []),
  'getAllMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getMissionById' : IDL.Func([IDL.Text], [Mission], ['query']),
  'getPlayerByName' : IDL.Func([IDL.Text], [Player], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mission = IDL.Record({
    'id' : IDL.Text,
    'completed' : IDL.Bool,
    'playerName' : IDL.Text,
  });
  const Player = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
  
  return IDL.Service({
    'createOrUpdateMission' : IDL.Func([Mission], [], []),
    'createOrUpdatePlayer' : IDL.Func([Player], [], []),
    'getAllMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getMissionById' : IDL.Func([IDL.Text], [Mission], ['query']),
    'getPlayerByName' : IDL.Func([IDL.Text], [Player], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };